@echo off
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
start www.nyan.cat
